
name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    name: SonarQube Scan
    runs-on: ubuntu-latest

    steps:
      # Step 1 - Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2 - Setup JDK (Maven project)
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3 - Cache Maven packages (optional but faster builds)
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4 - Run tests + SonarQube analysis
      - name: SonarQube Scan (skip tests)
        run: mvn clean verify sonar:sonar -DskipTests \
          -Dsonar.projectKey=dirtybank-api \
          -Dsonar.host.url=http://localhost:9000 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}